# Generated by Django 2.2.13 on 2020-08-23 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv_entry',
            name='dateEnd',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cv_entry',
            name='dateStart',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='education',
            name='dateEnd',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='education',
            name='dateStart',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cv_entry',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='facility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='grades',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
