# Generated by Django 2.2.13 on 2020-07-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_cv_entry_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('dob', models.DateField()),
                ('contactNumber', models.CharField(max_length=11)),
            ],
        ),
    ]
