# Generated by Django 2.2.13 on 2020-07-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0003_personaldetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.TextField()),
                ('grades', models.TextField()),
            ],
        ),
    ]
